//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCG.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCG.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alibi.
        /// </summary>
        internal static string Alibi {
            get {
                return ResourceManager.GetString("Alibi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alive.
        /// </summary>
        internal static string Alive {
            get {
                return ResourceManager.GetString("Alive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrested.
        /// </summary>
        internal static string Arrested {
            get {
                return ResourceManager.GetString("Arrested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassin.
        /// </summary>
        internal static string Assassin {
            get {
                return ResourceManager.GetString("Assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available from 9 players. Must kill everyone to win.
        /// </summary>
        internal static string AssassinDes {
            get {
                return ResourceManager.GetString("AssassinDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassing won.
        /// </summary>
        internal static string AssassinWon {
            get {
                return ResourceManager.GetString("AssassinWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach image.
        /// </summary>
        internal static string AttImage {
            get {
                return ResourceManager.GetString("AttImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilians won.
        /// </summary>
        internal static string CitizensWon {
            get {
                return ResourceManager.GetString("CitizensWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilian.
        /// </summary>
        internal static string Civilian {
            get {
                return ResourceManager.GetString("Civilian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple human. Sleeps at night. The only thing he can - vote.
        /// </summary>
        internal static string CivilianDes {
            get {
                return ResourceManager.GetString("CivilianDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Vibration.
        /// </summary>
        internal static string DeathVibr {
            get {
                return ResourceManager.GetString("DeathVibr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detective.
        /// </summary>
        internal static string Detective {
            get {
                return ResourceManager.GetString("Detective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last hope of this city. At night can identify player&apos;s side (dark / light).
        /// </summary>
        internal static string DetectiveDes {
            get {
                return ResourceManager.GetString("DetectiveDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian angel of this city. At night can save one player. Can&apos;t heal the same players two nights in a row.
        /// </summary>
        internal static string DoctorDes {
            get {
                return ResourceManager.GetString("DoctorDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don.
        /// </summary>
        internal static string Don {
            get {
                return ResourceManager.GetString("Don", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafia boss. At night checks if one of  the players is detective.
        /// </summary>
        internal static string DonDes {
            get {
                return ResourceManager.GetString("DonDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like nobody goes to jail today.
        /// </summary>
        internal static string DrawVote {
            get {
                return ResourceManager.GetString("DrawVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string ExitQ {
            get {
                return ResourceManager.GetString("ExitQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girl.
        /// </summary>
        internal static string Girl {
            get {
                return ResourceManager.GetString("Girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives an alibi to a player..., and a perfect night. At night can die only with chosen player. Can&apos;t give alibi to the same player two nights in a row.
        /// </summary>
        internal static string GirlDes {
            get {
                return ResourceManager.GetString("GirlDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        internal static string Heal {
            get {
                return ResourceManager.GetString("Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play.
        /// </summary>
        internal static string HowToPlay {
            get {
                return ResourceManager.GetString("HowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immortal.
        /// </summary>
        internal static string Immortal {
            get {
                return ResourceManager.GetString("Immortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available from 9 players. Simple civilian that can&apos;t die at night.
        /// </summary>
        internal static string ImmortalDes {
            get {
                return ResourceManager.GetString("ImmortalDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Name.
        /// </summary>
        internal static string InputName {
            get {
                return ResourceManager.GetString("InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input room password.
        /// </summary>
        internal static string InputPass {
            get {
                return ResourceManager.GetString("InputPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed.
        /// </summary>
        internal static string Killed {
            get {
                return ResourceManager.GetString("Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed.
        /// </summary>
        internal static string KilledPl {
            get {
                return ResourceManager.GetString("KilledPl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafia.
        /// </summary>
        internal static string Mafia {
            get {
                return ResourceManager.GetString("Mafia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must conquer this city. Kills at night. Hides at daytime.
        /// </summary>
        internal static string MafiaDes {
            get {
                return ResourceManager.GetString("MafiaDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafia won.
        /// </summary>
        internal static string MafiaWon {
            get {
                return ResourceManager.GetString("MafiaWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be empty.
        /// </summary>
        internal static string NameNotEmpty {
            get {
                return ResourceManager.GetString("NameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night - Girl.
        /// </summary>
        internal static string NichtGirl {
            get {
                return ResourceManager.GetString("NichtGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night - Detective.
        /// </summary>
        internal static string NightDetecive {
            get {
                return ResourceManager.GetString("NightDetecive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night - Doctor.
        /// </summary>
        internal static string NightDoctor {
            get {
                return ResourceManager.GetString("NightDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night - Don.
        /// </summary>
        internal static string NightDon {
            get {
                return ResourceManager.GetString("NightDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night - Mafia.
        /// </summary>
        internal static string NightMafia {
            get {
                return ResourceManager.GetString("NightMafia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night - Assassin.
        /// </summary>
        internal static string NightManiac {
            get {
                return ResourceManager.GetString("NightManiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody died tonight.
        /// </summary>
        internal static string NobodyDied {
            get {
                return ResourceManager.GetString("NobodyDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough players to start game.
        /// </summary>
        internal static string NotEnoghPlayers {
            get {
                return ResourceManager.GetString("NotEnoghPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Room.
        /// </summary>
        internal static string OpenRoom {
            get {
                return ResourceManager.GetString("OpenRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Connected.
        /// </summary>
        internal static string PlayersConnected {
            get {
                return ResourceManager.GetString("PlayersConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug report / Wish.
        /// </summary>
        internal static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Pass.
        /// </summary>
        internal static string RoomPass {
            get {
                return ResourceManager.GetString("RoomPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Title.
        /// </summary>
        internal static string RoomTitle {
            get {
                return ResourceManager.GetString("RoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Title can&apos;t be empty.
        /// </summary>
        internal static string RoomTitleNotEmpty {
            get {
                return ResourceManager.GetString("RoomTitleNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather with friends (Minimum player count - 6).
        /// </summary>
        internal static string Rule1 {
            get {
                return ResourceManager.GetString("Rule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a moderator.
        /// </summary>
        internal static string Rule2 {
            get {
                return ResourceManager.GetString("Rule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a single wi-fi network (some public networks may not suit). Create room and connect.
        /// </summary>
        internal static string Rule3 {
            get {
                return ResourceManager.GetString("Rule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow moderator&apos;s instructions.
        /// </summary>
        internal static string Rule4 {
            get {
                return ResourceManager.GetString("Rule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicate and have fun!.
        /// </summary>
        internal static string Rule5 {
            get {
                return ResourceManager.GetString("Rule5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server stoped.
        /// </summary>
        internal static string ServerStoped {
            get {
                return ResourceManager.GetString("ServerStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to Main Menu.
        /// </summary>
        internal static string ToMainMenu {
            get {
                return ResourceManager.GetString("ToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        internal static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish.
        /// </summary>
        internal static string Wish {
            get {
                return ResourceManager.GetString("Wish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        internal static string WrongPass {
            get {
                return ResourceManager.GetString("WrongPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current network is unsuitable.
        /// </summary>
        internal static string WrongWifi {
            get {
                return ResourceManager.GetString("WrongWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
